### ISSUE TITLE
Is .idea folder necessary?

### ISSUE THREAD

**Issue by RangHo** [UniGDC/H.E.L.L.#1]
I observe that folder is being updated every time we edit stuff using Rider.

I think the content of that folder is machine-specific, so it might be better for us to make git ignore the folder.

**Comment by syy1125** [comment]
Here is JetBrain's official answer:
https://rider-support.jetbrains.com/hc/en-us/articles/207097529-What-is-the-idea-folder-

**Comment by RangHo** [comment]
hmm, it sounds like it is necessary to keep that folder in the repository.
I found JetBrains gitignore file, so I'll just add that gitignore content to our gitignore file, just in case.
